#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="e107%20v2.3.0/e107_2.3.0_full.tar.gz"
URL="http://sourceforge.net/projects/e107/files/e107/$VERSION"

dl $URL /usr/local/src

