#!/bin/sh -ex

DB_NAME=e107
DB_USER=e107
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/e107

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf $SRC/e107_*_full.tar.gz -C $WEBROOT
rm $SRC/e107_*_full.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/e107_media
chown -R www-data:www-data $WEBROOT/e107_system
chown -R www-data:www-data $WEBROOT/e107_themes
chown -R www-data:www-data $WEBROOT/e107_images
chown -R www-data:www-data $WEBROOT/e107_plugins
chown www-data:www-data $WEBROOT/e107_config.php

# configure apache
a2dissite 000-default
a2ensite e107
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"


# curl based install

EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

do_curl() {
    URL="http://127.0.0.1/install.php"
    CURL="curl -c /tmp/cookie -b /tmp/cookie"
    #OUT=$($CURL $URL --data "$1")

    $CURL $URL --data "$1" | \
         grep previous_steps | \
         sed -e "s|.*value='\(.*\)'.*|\1|"
}

PREV=$(do_curl)
PREV=$(do_curl "previous_steps=$PREV&stage=2&language=English&start=Continue+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=3&server=localhost&name=$DB_USER&password=$DB_PASS&db=$DB_NAME&db_utf8=1&prefix=e107_&createdb=1&submit=Continue+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=3&overwritedb=Overwrite+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=4&submit=Continue+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=5&continue_install=Continue+%CE%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=6&u_name=$ADMIN_NAME&d_name=Administrator&pass1=$ADMIN_PASS&pass2=$ADMIN_PASS&email=$EMAIL&submit=Continue+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=7&sitename=example&sitetheme=landingzero&install_plugins=1&generate_content=1&submit=Continue+%C2%BB")
PREV=$(do_curl "previous_steps=$PREV&stage=8&submit=Continue+%C2%BB")

rm -f $WEBROOT/install.php
rm -f /tmp/cookie

# secure sensitive files
chmod 640 $WEBROOT/e107_config.php

# enable defaults
mv $WEBROOT/e107.htaccess $WEBROOT/.htaccess
mv $WEBROOT/e107.robots.txt $WEBROOT/robots.txt

# stop services
service mysql stop
service apache2 stop

