#!/bin/sh -ex

DB_NAME=e107
DB_USER=e107
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/e107

# unpack and set permissions
mkdir -p $WEBROOT
tar -zxf $SRC/e107_*_full.tar.gz -C $WEBROOT
rm $SRC/e107_*_full.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/e107_files
chown -R www-data:www-data $WEBROOT/e107_themes
chown -R www-data:www-data $WEBROOT/e107_images
chown -R www-data:www-data $WEBROOT/e107_plugins
chown www-data:www-data $WEBROOT/e107_config.php

# configure apache
a2dissite default
a2ensite e107
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

