#!/bin/bash -e
# regenerate e107 mysql password

. /etc/default/inithooks

CONF=/var/www/e107/e107_config.php

PASSWORD=$(mcookie)
sed -i "s|^\$mySQLpassword.*|\$mySQLpassword       = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=e107 --pass="$PASSWORD"

